/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentportal;


import java.sql.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class ViewReport extends javax.swing.JFrame {

    String student_id,nm,clss,d,crs,username,pswrd;
    
    public ViewReport() {
        initComponents();
    }

    public void result(String s1,String s2,String s3,String s4,String s5,String s6,String s7)
    { 
        student_id=s1;
        nm=s2;
        clss=s3;
        d=s4;
        crs=s5;
        username=s6;
        pswrd=s7;
        usrnm.setText(s6+"");   
        try{
        ArrayList<User> list=Report();
        DefaultTableModel m=(DefaultTableModel) Report.getModel();
        Object[] row=new Object[3];
        for(int i=0;i<list.size();i++){
            for(int j=0;j<6;j++){
            row[0]=list.get(i).subject[j];
            row[1]=list.get(i).marks[j];
            row[2]=list.get(i).attendance[j];
            m.addRow(row);
            }
        }
        }  catch(Exception e){System.out.println(e);}
        
    }
    
    public ArrayList<User> Report(){
        ArrayList<User> list=new ArrayList<>();
        try{
            Connection con=StudentPortal.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from marks m inner join attendance a on m.student_id=a.student_id where m.student_id='"+student_id+"'");
            User user;
            float marks[]=new float[8];
            float atten[]=new float[15];
            String subjects[]={"Java","DE","COA","DS","Mathematics","EVS"};
            while(rs.next()){
                for(int i=1;i<=7;i++){
                    marks[i]=rs.getFloat(i);
                }
                for(int i=8;i<=14;i++){
                    atten[i]=rs.getFloat(i);
                }
                user=new User(marks,atten,subjects);
                list.add(user);
            }
        }
        catch(Exception e){}
        return list;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Report = new javax.swing.JTable();
        goback = new javax.swing.JButton();
        usrnm = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username");

        Report.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject", "Marks", "Attendace"
            }
        ));
        jScrollPane3.setViewportView(Report);

        goback.setText("<--Back");
        goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(goback)
                        .addGap(327, 327, 327))))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(usrnm, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(goback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usrnm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackActionPerformed
        NavigateProfile fr=new NavigateProfile();
        fr.setVisible(true);
        fr.login(student_id,nm,clss,d,crs,username,pswrd);     
        dispose();
    }//GEN-LAST:event_gobackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Report;
    private javax.swing.JButton goback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel usrnm;
    // End of variables declaration//GEN-END:variables
    
    private static class User {
        private float marks[]=new float[8];
        private float attendance[]=new float[8];
        private String subject[]=new String[6];
        public User(float marks[],float attendance[],String[] subject) {
            //System.out.println("user");
            try{
            for(int i=0;i<6;i++){
                this.marks[i]=marks[i+2];
                //System.out.println(this.marks[i]);
            }
            for(int i=0;i<6;i++){
                this.attendance[i]=attendance[i+9];
                //System.out.println(this.attendance[i]);
            }
            for(int i=0;i<6;i++){
                this.subject[i]=subject[i];
                //System.out.println(subject[i]);
            }
            }catch(Exception e){System.out.println(e);}
        }

        public float[] getMarks() {
            return marks;
        }

        public float[] getAttendance() {
            return attendance;
        }

        public String[] getSubject() {
            return subject;
        }

        
    }
}
